### ISSUE TITLE
pridat do zoznamu slova bez diakritiky

### ISSUE THREAD

**Issue by dankez** [rostacik/slovenske-nadavky#3]
ahoj,  
mne by sa hodil zoznam slov aj bez diakritiky pretoze vela ludi proste pise takto. 

plus mozno by satalo za pokus  aj zoznam slov pisanych s medzerami alebo inym oddelovnikom k o k o .... vsak sa asi chapme. 
-  pre inspiraciu staci zajst do diskusii sme.sk a pod.

**Comment by rostacik** [comment]
ahoj.
jasné, vieme čo všetko sa dá použiť namiesto o alebo pod. hlava pochopí a slovo prejde :) no IMHO by to mala urobiť mašina pri compare, napr takto : 

https://stackoverflow.com/questions/359827/ignoring-accented-letters-in-string-comparison

diakritika je accent takže ak porovnáš bez tak by ti aj slovo s diakritikou aj bez malo hodiť zhodu. tie spaces a tak pod, netuším v čom tie slová porovnávaš, v akom jazyku, ktorý má aké features ohľadom stringov. 

ak chceš, mohli by sme urobiť branch so slovami bez diakritiky... neviem či by to nejak pomohlo. s tým, že by si ľudia mohli vziať ktorý potrebujú, keby chceli oba. branche by boli in sync.

**Comment by dankez** [comment]
ahoj, 
pouzivam wp a ich komentovaci system bez upravy kodu. ked som teraz skusal napisat 2 slova bez diakritiky tak vyzera ze to vyfiltrovalo. takze moja reakcia je bezpredmetna.

**Comment by rostacik** [comment]
OK then, takže zatváram :)
